---
site_description: My personal notes
site_author: Diego
site_url: https://diefergil.github.io/personal-notes
site_name: My personal notes

nav:
  - Home: index.md
  - Python:
      - Environments:
          - Virtual environments: python/environments.md
      - Natural language processing:
          - HuggingFace: python/nlp/huggingface.md
      - Tests:
          - Pytests: python/pytest.md
  - About: about.md

plugins:
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - autolinks
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
  - section-index
  - mkdocs-newsletter
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_ads_txt"
  - tags

markdown_extensions:
  - abbr
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: "!!python/name:pymdownx.emoji.to_svg"
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css, stylesheets/links.css]

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/diefergil
    - icon: fontawesome/solid/rss
      link: >-
        https://diefergil.github.io/personal-notes/newsletter/0_newsletter_index
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-6S6TNHYVRT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank"
            rel="noopener">feedback form</a>.

repo_name: diefergil/personal-notes
repo_url: https://github.com/diefergil/personal-notes
