---
site_description: My personal notes
site_author: Diego
site_url: https://diefergil.github.io/personal-notes
site_name: My personal notes

nav:
  - Home: index.md
  - Cloud:
      - AWS:
          - App Runner: cloud/aws/app_runner.md
          - Batch: cloud/aws/batch.md
          - Lambda functions: cloud/aws/lambda.md
          - Steps: cloud/aws/steps.md
      - Google Cloud:
          - gcloud CLI: cloud/google/gcloud.md
          - App Engine: cloud/google/app_engine.md
          - Cloud Functions: cloud/google/cloud_functions.md
          - Cloud Run: cloud/google/cloud_run.md
          - Bigquery: cloud/google/Bigquery.md
  - Generative AI:
      - Introduction: generative_ai/introduction.md
      - NLP: generative_ai/nlp/Natural Language Processing.md
      - Adapting foundational models:
          - Prompting: generative_ai/prompting.md
          - Instruction Fine-Tuning: generative_ai/Fine Tuning.md
          - Reinforcement Learning From Human Feedback: generative_ai/Reinforcement Learning From Human Feedback.md
          - Probing: generative_ai/probing.md
      - Evaluation: generative_ai/Evaluate LLMs.md
      - Deployment: generative_ai/Deploy LLMS.md
      - HuggingFace:
          - Overview: generative_ai/huggingface.md
          - Key components: generative_ai/tutorials/hugginface_intro.ipynb
          - Tokenizer: generative_ai/tutorials/hugging-face-tokenizer.ipynb
          - Difussers: generative_ai/tutorials/diffusers.ipynb
      - Embeddings:
          - Lance DB: generative_ai/tutorials/lance_db.ipynb
          - Lance DB Multimodal: generative_ai/tutorials/lance_db_multimodal.ipynb # yamllint disable-line
      - Tutorials:
          - Pytorch: generative_ai/tutorials/pytorch_intro.ipynb
          - Promting techniques workflow:
              - generative_ai/tutorials/try_promt_techniques.ipynb
              - generative_ai/tutorials/Building_QA_Datasets.ipynb
              - generative_ai/tutorials/wikipedia_qa.ipynb
          - React promt example: generative_ai/tutorials/example_ReAcT_prompt.ipynb # yamllint disable-line
          - Open AI call function: generative_ai/tutorials/openai_functions.ipynb # yamllint disable-line
          - Langchain parser chain: generative_ai/tutorials/langchain_examples.ipynb # yamllint disable-line
          - Transfer Learning:
              - Retrain mobilenet:
                  - generative_ai/tutorials/transfer-learning-mobilenet.ipynb
          - GANs: generative_ai/tutorials/train_gans.ipynb
          - DDPM: generative_ai/tutorials/training_DDPM.ipynb
          - Langchain:
              - generative_ai/tutorials/langchain/snnipets.md
              - generative_ai/tutorials/langchain/agents/Lesson_2_Student.ipynb
              - generative_ai/tutorials/langchain/agents/Lesson_4_Student.ipynb
              - generative_ai/tutorials/langchain/agents/Lesson_5_Student.ipynb
              - generative_ai/tutorials/langchain/agents/helper.py
              - generative_ai/tutorials/langchain/functions/L2-lcel-student.ipynb
              - generative_ai/tutorials/langchain/functions/L5-tools-routing-apis-student.ipynb
              - generative_ai/tutorials/langchain/functions/L6-functional_conversation-student.ipynb
  - Mlops:
      - Introduction: mlops/mlops_intro.md
      - Continous integration: mlops/continous_delivery.md
      - Tools:
          - Docker: mlops/tools/Docker.md
          - Github actions: mlops/tools/github_actions.md
          - Makefile: mlops/tools/makefile.md
  - Python:
      - API's:
          - Best practices: python/apis/best_practices.md
          - FastAPI: python/apis/fastapi.md
          - Flask: python/apis/flask.md
      - CLI's:
          - Argparse: python/cli/argparse.md
          - Click: python/cli/click.md
      - Environments:
          - Virtual environments: python/environments.md
      - Packaging:
          - Setuptools: python/packaging/setuptools.md
          - Poetry: python/packaging/Poetry.md
      - Tests:
          - Pytests: python/pytest.md
  - Infrastructure:
      - Pulumi: IAC/Pulumi.md
      - Terraform: IAC/Terraform.md
  - About: about.md

plugins:
  - search
  - exclude-search:
      exclude: [newsletter/*]
  - autolinks
  - git-revision-date-localized:
      type: timeago
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true
      strict: false
  - minify:
      minify_html: true
  - section-index
  # mkdocs-newsletter
  # TODO: check if it works & the problem with git in docker
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.hooks:copy_ads_txt"
  - tags
  - mermaid2:
      arguments:
        securityLevel: loose
  - mkdocs-jupyter:
      execute: false
      allow_errors: false
      show_input: true

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - def_list
  - toc:
      permalink: ⚑
      baselevel: 2
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        # Mermaid diagrams
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
theme:
  name: material
  custom_dir: theme
  logo: img/logo.bmp
  features:
    - navigation.footer
    - navigation.instant
    - navigation.top
    - content.code.annotate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.select

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css: [stylesheets/extra.css, stylesheets/links.css]

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/diefergil
    - icon: fontawesome/solid/rss
      link: >-
        https://diefergil.github.io/personal-notes/newsletter/0_newsletter_index
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-6S6TNHYVRT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank"
            rel="noopener">feedback form</a>.

extra_javascript:
  - optionalConfig.js
  - https://unpkg.com/mermaid@9.4.0/dist/mermaid.min.js
  - extra-loader.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_name: diefergil/personal-notes
repo_url: https://github.com/diefergil/personal-notes
