name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.10.15
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.15'

      - name: Install PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.10.15
          allow-python-prereleases: false

      - name: Clear Python Cache
        run: |
          sudo rm -rf /home/runner/.cache/pdm

      - name: Install dependencies
        run: make install

      - name: Update requirements
        run: make update

      - name: Make the newsletters
        run: make build-newsletters

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add pdm.lock
          git add docs/newsletter
          git diff-index --quiet HEAD \
            || git commit -m "chore: update dependency and publish newsletters"

      - name: Make the site
        run: make build-docs

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
